services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\WalmartController:
        public: true
        arguments: ['@App\Service\WalmartAuthService']

    App\Service\WalmartAuthService:
        arguments:
            $clientId: '%env(WALMART_CLIENT_ID)%'
            $clientSecret: '%env(WALMART_CLIENT_SECRET)%'
            $wmSvcName: 'Your-Walmart-Service-Name'

    App\Controller\ProductController:
        arguments:
            $walmartAuthService: '@App\Service\WalmartAuthService'